services:
  snort3:
    build: .
    image: mikehorn/snort3
    container_name: snort3
    stdin_open: true
    tty: true
    security_opt:
      - "no-new-privileges:true"
    read_only: true
    network_mode: "host"
    volumes:
      - /home/$USER/snort:/files
